import { CurrencyPipe } from '@angular/common';
import { Component, DestroyRef, inject, OnInit, signal } from '@angular/core';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { finalize } from 'rxjs';
import { ModeloIconeDetalhe } from '../../models/admin.model';
import { AdminService } from '../../services/admin.service';

@Component({ selector: 'app-modelos-admin-page', imports: [CurrencyPipe, ReactiveFormsModule], templateUrl: './modelos-admin-page.html', styleUrl: './modelos-admin-page.scss' })
export class ModelosAdminPage implements OnInit {
  private readonly service = inject(AdminService); private readonly destroyRef = inject(DestroyRef); private readonly fb = inject(FormBuilder);
  protected readonly items = signal<ModeloIconeDetalhe[]>([]); protected readonly message = signal<string | null>(null);
  protected readonly editingId = signal<number | null>(null); protected readonly formVisible = signal(false); protected readonly saving = signal(false);
  protected readonly form = this.fb.nonNullable.group({ nome: ['', [Validators.required, Validators.maxLength(120)]], descricao: ['', [Validators.required, Validators.maxLength(10000)]], imagemUrl: ['', Validators.maxLength(2000)], precoBase: [0, [Validators.required, Validators.min(0)]], ativo: [true], historia: ['', Validators.maxLength(10000)], significado: ['', Validators.maxLength(10000)], simbologia: ['', Validators.maxLength(10000)], oracao: ['', Validators.maxLength(10000)], ocasiaoPresente: ['', Validators.maxLength(10000)], cuidados: ['', Validators.maxLength(10000)] });
  ngOnInit(): void { this.load(); }
  protected load(): void { this.service.modelos().pipe(takeUntilDestroyed(this.destroyRef)).subscribe({ next: (x) => this.items.set(x), error: () => this.message.set('Não foi possível carregar os modelos.') }); }
  protected newModel(): void { this.editingId.set(null); this.form.reset({ nome: '', descricao: '', imagemUrl: '', precoBase: 0, ativo: true, historia: '', significado: '', simbologia: '', oracao: '', ocasiaoPresente: '', cuidados: '' }); this.formVisible.set(true); this.message.set(null); }
  protected edit(item: ModeloIconeDetalhe): void { const d = item.conteudoDevocional; this.editingId.set(item.id); this.form.reset({ nome: item.nome, descricao: item.descricao, imagemUrl: item.imagemUrl ?? '', precoBase: item.precoBase, ativo: item.ativo, historia: d?.historia ?? '', significado: d?.significado ?? '', simbologia: d?.simbologia ?? '', oracao: d?.oracao ?? '', ocasiaoPresente: d?.ocasiaoPresente ?? '', cuidados: d?.cuidados ?? '' }); this.formVisible.set(true); this.message.set(null); window.scrollTo({ top: 0, behavior: 'smooth' }); }
  protected cancel(): void { this.formVisible.set(false); this.editingId.set(null); }
  protected save(): void { if (this.form.invalid || this.saving()) { this.form.markAllAsTouched(); return; } const v = this.form.getRawValue(); const optional = (text: string) => text.trim() || null; const devotional = { historia: optional(v.historia), significado: optional(v.significado), simbologia: optional(v.simbologia), oracao: optional(v.oracao), ocasiaoPresente: optional(v.ocasiaoPresente), cuidados: optional(v.cuidados) }; const request = { nome: v.nome.trim(), descricao: v.descricao.trim(), imagemUrl: optional(v.imagemUrl), precoBase: Number(v.precoBase), ativo: v.ativo, conteudoDevocional: Object.values(devotional).some(Boolean) ? devotional : null }; const id = this.editingId(); const operation = id === null ? this.service.criarModelo(request) : this.service.atualizarModelo(id, request); this.saving.set(true); operation.pipe(takeUntilDestroyed(this.destroyRef), finalize(() => this.saving.set(false))).subscribe({ next: (saved) => { this.items.update((all) => id === null ? [saved, ...all] : all.map((item) => item.id === saved.id ? saved : item)); this.cancel(); this.message.set(id === null ? 'Modelo cadastrado com sucesso.' : 'Modelo atualizado com sucesso.'); }, error: () => this.message.set('Não foi possível salvar o modelo. Revise os campos informados.') }); }
  protected disable(id: number): void { if (!confirm('Deseja desativar este modelo do catálogo?')) return; this.service.desativarModelo(id).subscribe({ next: () => this.items.update((all) => all.map((x) => x.id === id ? { ...x, ativo: false } : x)), error: () => this.message.set('Não foi possível desativar o modelo.') }); }
}
